# Generated by Django 4.2.5 on 2023-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelconsumption",
            name="enginesize",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
