# Generated by Django 4.2.5 on 2023-09-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0002_alter_fuelconsumption_enginesize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelconsumption",
            name="fuelconsumption_city",
            field=models.DecimalField(decimal_places=2, max_digits=90),
        ),
        migrations.AlterField(
            model_name="fuelconsumption",
            name="fuelconsumption_comb",
            field=models.DecimalField(decimal_places=2, max_digits=90),
        ),
        migrations.AlterField(
            model_name="fuelconsumption",
            name="fuelconsumption_hwy",
            field=models.DecimalField(decimal_places=2, max_digits=90),
        ),
    ]
