# Generated by Django 4.2.5 on 2023-09-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0004_weatherdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="Date_Month",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="Date_Week_of",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="Date_Year",
        ),
    ]
