# Generated by Django 4.2.5 on 2023-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0005_remove_weatherdata_date_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernumber", models.IntegerField()),
                ("quantityordered", models.IntegerField()),
                ("priceeach", models.DecimalField(decimal_places=2, max_digits=5)),
                ("orderlinenumber", models.IntegerField()),
                ("sales", models.DecimalField(decimal_places=2, max_digits=5)),
                ("orderdate", models.DateField()),
                ("status", models.CharField(max_length=25)),
                ("qtr_id", models.IntegerField()),
                ("month_id", models.IntegerField()),
                ("year_id", models.IntegerField()),
                ("productline", models.CharField(max_length=25)),
                ("msrp", models.IntegerField()),
                ("productcode", models.CharField(max_length=10)),
                ("customername", models.TextField()),
                ("city", models.CharField(max_length=25)),
                ("state", models.CharField(max_length=25)),
                ("country", models.CharField(max_length=25)),
                ("contactlastname", models.CharField(max_length=25)),
                ("contactfirstname", models.CharField(max_length=25)),
                ("dealsize", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Sales data",
            },
        ),
    ]
