# Generated by Django 4.2.5 on 2023-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0006_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sales",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
