# Generated by Django 4.2.5 on 2023-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0007_alter_sales_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="state",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
