# Generated by Django 4.2.5 on 2023-09-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0008_alter_sales_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="state",
        ),
    ]
