# Generated by Django 4.2.5 on 2023-09-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0009_remove_sales_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="month_id",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="orderlinenumber",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="qtr_id",
        ),
    ]
