# Generated by Django 4.2.5 on 2023-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empstat", "0010_remove_sales_month_id_remove_sales_orderlinenumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.IntegerField(),
        ),
    ]
